### ISSUE TITLE
Bone Meal for Tarma Root, Desert Novas, Wakeblooms not working

### ISSUE THREAD

**Issue by uberwookie** [DrasticDemise/Simply-Magic#19]
Does not seem to work as stated in the quest book. I started with the .8(?) pack and am using the most recent (with the new Aura Cascade quests).

I tried fully lit underground caves, unlit ones, on stone, andesite, dioriate, ore, dirt, and gravel at ly coords between 40-15 and did not get any tarma root, and under witchwood trees used 20+ bonemeal with no saplings (one time I got one without bonemealing though...) and have not been able to get wakeblooms or desert novas from any biome/block they should spawn on.

**Comment by uberwookie** [comment]
I tried ocean biomes, river, swamp and under leaves, not under leaves, in pure dark, and on 4 phases of the moon for wakebloom, and desert novas i tried beaches and actual deserts both during night and day.

**Comment by Zieg777** [comment]
I should rewrite the questbook then. AM2 by default is supposed to work by letting you bonemeal sand (for desert nova), water (wakebloom), stone (in the dark, for tarma root). Grass should get you cerublossom no problem. Unfortunately, that doesn't actually work, since the game says you can only bonemeal grass.

AM2 plantfix fixes this. You still have to bonemeal grass though. Make a dark room with stone, and a single spot of grass in the middle. A stack of bonemeal should net you a few tarma root (not many). Similarly with grass and a pool of water for wakebloom, and grass and a sand room for desert nova.

Also of course, the AM2 grow spell should work in these same places. I'd imagine other mod's growth boosters (that act as bonemeal at least) should work as well.
