### ISSUE TITLE
Additional Inventory Storage [Discussion]

### ISSUE THREAD

**Issue by DrasticDemise** [DrasticDemise/Simply-Magic#25]
Looking for some feedback on current inventory management. You can find the strawpoll here: http://strawpoll.me/6673468

Do you find additional inventory storage lacking enough to warrant an additional mod such as baggineses?

**Comment by TDarkShadow** [comment]
At the moment, my problem isn't mobile storage but cobble (and other stones) storage. Maybe a barrel mod like JABBA?

**Comment by nicogranelli** [comment]
I added a bunch of mods to my playthrough with the intention to test them and report. This are my findings so far related to storage (everything was added considering the basic premise of not overshadowing features in the magic mods and nothing better than iron in tools): 

* Bagginses
Configured as in regrowth, with every color accepting everything. Very good at early game, and you can keep using them, or change them for Witching gadgets options later.

* Jabba
I hate playing without these barrels, so I added them. But, I removed the Diamond Dolly. Having to travel to your mob farms in fun (I built 3 farms around spawners I found while exploring). Lots of space to tweak the upgrades (magic metals instead of Iron for upgrades for example). I haven't used BSpace upgrades yet, but probably they should get removed in favor of builds with magic mirrors or flickers

* Enhanced Inventories
Nice alternative to iron chests. Recipes can be tweaked to use magic metals. Also added the mod that adds a compatible dolly (jabba one doesn't work with this mod), but I haven't had the chance the test it. The autocrafter should be removed, as is way out of theme, and it is pretty buggy.

* Bibliocraft
Potion shelves and Book cases are really good, specially in a magic themed modpack. It also adds utilities that work very well with a "closer to vanilla" gameplay, specially in early game.

* StorageDrawers
With the addons for magical woods. The controller might be too powerful, but it helps in early games mob farms, with a hopper into a wall to sort drops, all to way to inventarium late game

* Hopper Duct Mod
I added just to see if it was OP in this context. But the "pipes" it add are not really pipes. They are just ways to extend a hopper. You can't use them like smart pipes of other mods. They are pretty dumb :). Also the filtered hopper is a nice addition, pretty vanilla style.

**Comment by TDarkShadow** [comment]
@nicogranelli What about this one? http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1442380-betterstorage-0-13-1-127-wip
Would also provide some PvP mechanic for on servers.

**Comment by nicogranelli** [comment]
@TDarkShadow looks cool. I haven't use it yet

**Comment by Zieg777** [comment]
I've made myself a handful of Witching Gadgets bags. I do wish they were at least a chest size though. They can be dyed, as well as renamed in the anvil. KAMI's bag is of course huge.

For storage.. I do miss storage drawers still. My main problem is I can't easily upgrade my Iron Chests. When I upgrade them, it makes my flicker crystals pop off, so I have to reset them.

**Comment by DrasticDemise** [comment]
Added Jabba, Bibliocraft, and a quest indicating the usefulness of Witching Gadgets for inventory space. Thank you for everyones input!
