### ISSUE TITLE
[Suggestions] :)

### ISSUE THREAD

**Issue by fireflyacire** [DrasticDemise/Simply-Magic#45]
1. Fix Witchery where it doesn't go straight to end game quests.
2. Add more Ars Magic quests. (Make each guardian its own quest)
3. Maybe look into adding chromaticraft with its own quest line.

PS Fin sent me! :D

**Comment by DrasticDemise** [comment]
1. The witchery line is set up so that players may start on the Vampirism at the beginning of the game. This is intended because it **is** possible to become a vampire without starting Witchery.

2. This will be considered.

3. Reika's mods do not have a license I agree with, thus they will not be in any packs of mine.
